#!/bin/bash

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC="uwsgi daemon"
NAME=##INSTANCE##
DAEMON=##UWSGI_PROC##
CONFIGFILE=/etc/##UWSGI_CONFIG##
PIDFILE=##UWSGI_PID##
SCRIPTNAME=/etc/init.d/$NAME

set -e
[ -x "$DAEMON" ] || exit 0

do_start() {
    LC_ALL='en_US.UTF-8' LANG='en_US.UTF-8'
    $DAEMON $CONFIGFILE || echo -n "uwsgi already running"
}

do_stop() {
    $DAEMON --stop $PIDFILE || echo -n "uwsgi not running"
    rm -f $PIDFILE
    echo "$DAEMON STOPED."
}

do_reload() {
    $DAEMON --reload $PIDFILE || echo -n "uwsgi can't reload"
}

do_status() {
    ps aux|grep $DAEMON
}

case "$1" in
 status)
    echo -en "Status $NAME: \n"
    do_status
 ;;
 start)
    echo -en "Starting $NAME: \n"
    do_start
 ;;
 stop)
    echo -en "Stopping $NAME: \n"
    do_stop
 ;;
 reload|graceful)
    echo -en "Reloading $NAME: \n"
    do_reload
 ;;
 restart)
    echo -en "Restarting $NAME: \n"
    $0 stop
    $0 start
 ;;
 *)
    echo "Usage: $SCRIPTNAME {start|stop|reload|restart}" >&2
    exit 3
 ;;
esac

exit 0

